dist: trusty
sudo: required
language: php

addons:
  mariadb: 10.1

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

notifications:
  on_success: never
  on_failure: never
  webhooks:
    on_success: always
git:
  depth: 1

install:
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -u root -e 'create database telegrambot; use telegrambot; source structure.sql;'

script:
  - composer check-code
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] ; then composer test-cov; else composer test; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then composer test-cov-upload; fi
